import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { AnalyticsRow } from '../types'
import { inr, n, s } from '../lib/format'
const palette = ['#5b8cff', '#22c55e', '#a78bfa', '#f59e0b', '#06b6d4', '#ef6a78']
const tooltip = { contentStyle: { background: '#151d2e', border: '1px solid #2b3852', borderRadius: 8 }, labelStyle: { color: '#cbd5e1' }, itemStyle: { color: '#f8fafc' }, formatter: (value: number) => inr(value, false) }
export function RevenueChart({ sales, profit }: { sales: AnalyticsRow[]; profit: AnalyticsRow[] }) { const merged = sales.map((row, index) => ({ month: s(row, 'year_month'), revenue: n(row, 'revenue'), profit: n(profit[index] ?? {}, 'profit') })); return <ResponsiveContainer width="100%" height={300}><LineChart data={merged}><CartesianGrid vertical={false} stroke="#243049"/><XAxis dataKey="month" tick={{ fill: '#8f9db3', fontSize: 11 }} tickLine={false} axisLine={false}/><YAxis tickFormatter={value => inr(value)} tick={{ fill: '#8f9db3', fontSize: 11 }} tickLine={false} axisLine={false}/><Tooltip {...tooltip}/><Legend/><Line type="monotone" dataKey="revenue" name="Revenue" stroke="#5b8cff" strokeWidth={2.5} dot={false}/><Line type="monotone" dataKey="profit" name="Profit" stroke="#22c55e" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer> }
export function CategoryChart({ data }: { data: AnalyticsRow[] }) { return <ResponsiveContainer width="100%" height={300}><PieChart><Pie data={data} dataKey="revenue" nameKey="category" innerRadius={62} outerRadius={98} paddingAngle={3}>{data.map((_, index) => <Cell key={index} fill={palette[index % palette.length]}/>)}</Pie><Tooltip {...tooltip}/><Legend formatter={value => <span className="legend-text">{value}</span>}/></PieChart></ResponsiveContainer> }
export function RegionChart({ data }: { data: AnalyticsRow[] }) { return <ResponsiveContainer width="100%" height={285}><BarChart data={data} layout="vertical" margin={{ left: 10 }}><XAxis type="number" hide/><YAxis type="category" dataKey="region" width={62} tick={{ fill: '#aab6c8', fontSize: 12 }} tickLine={false} axisLine={false}/><Tooltip {...tooltip}/><Bar dataKey="revenue" name="Revenue" fill="#5b8cff" radius={[0, 4, 4, 0]}/></BarChart></ResponsiveContainer> }
export function SegmentChart({ data }: { data: AnalyticsRow[] }) { return <ResponsiveContainer width="100%" height={260}><BarChart data={data}><CartesianGrid vertical={false} stroke="#243049"/><XAxis dataKey="customer_segment" tick={{ fill: '#8f9db3', fontSize: 11 }} tickLine={false} axisLine={false}/><YAxis tickFormatter={value => inr(value)} tick={{ fill: '#8f9db3', fontSize: 11 }} tickLine={false} axisLine={false}/><Tooltip {...tooltip}/><Bar dataKey="revenue" name="Revenue" fill="#a78bfa" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer> }
export function ChannelChart({ data }: { data: AnalyticsRow[] }) { return <ResponsiveContainer width="100%" height={260}><BarChart data={data}><CartesianGrid vertical={false} stroke="#243049"/><XAxis dataKey="sales_channel" tick={{ fill: '#8f9db3', fontSize: 11 }} tickLine={false} axisLine={false}/><YAxis tickFormatter={value => inr(value)} tick={{ fill: '#8f9db3', fontSize: 11 }} tickLine={false} axisLine={false}/><Tooltip {...tooltip}/><Bar dataKey="revenue" name="Revenue" fill="#22c55e" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer> }
export function StatusChart({ data }: { data: AnalyticsRow[] }) { return <ResponsiveContainer width="100%" height={260}><PieChart><Pie data={data} dataKey="transactions" nameKey="order_status" innerRadius={58} outerRadius={92} paddingAngle={3}>{data.map((_, index) => <Cell key={index} fill={palette[index % palette.length]}/>)}</Pie><Tooltip/><Legend formatter={value => <span className="legend-text">{value}</span>}/></PieChart></ResponsiveContainer> }
