import { useEffect, useState } from 'react'
import { ArrowDown, Braces, CheckCircle2, Database, FileSpreadsheet, Layers3, Network, ServerCog, Sparkles } from 'lucide-react'
import { loadPipelineStatus } from '../api'
import { number } from '../lib/format'
import type { PipelineStatus } from '../types'
import { LoadingSkeleton } from './LoadingSkeleton'
import './pipeline.css'

const stages = [[FileSpreadsheet, 'Raw Sales Data', 'Transactional source records'], [Database, 'CSV Data Source', 'sales.csv landing dataset'], [Sparkles, 'Apache Spark', 'Distributed processing runtime'], [CheckCircle2, 'Data Cleaning', 'Quality rules and normalization'], [Braces, 'PySpark Transformations', 'Feature engineering at scale'], [Layers3, 'Aggregation Engine', 'Dimensional Spark analytics'], [ServerCog, 'FastAPI', 'JSON analytics service'], [Network, 'React Analytics Dashboard', 'Interactive decision workspace']]
const steps = [['Schema Validation', 'Applies an explicit Spark schema and flags malformed values as nulls.'], ['Duplicate Removal', 'Removes repeated transaction identifiers before metrics are calculated.'], ['Missing Value Handling', 'Fills allowed descriptive gaps and safely defaults missing discounts.'], ['Data Type Conversion', 'Converts dates, quantities, and financial values into analytical types.'], ['Revenue Validation', 'Recalculates canonical revenue from quantity, price, and discount.'], ['Feature Engineering', 'Adds period, discount amount, profit, and profit-margin fields.'], ['Distributed Aggregations', 'Uses Spark groupings, windows, and cached DataFrames for metrics.'], ['API Serialization', 'Converts Spark result rows into predictable JSON responses.']]
export function PipelinePage() { const [status, setStatus] = useState<PipelineStatus | null>(null); const [failed, setFailed] = useState(false); useEffect(() => { loadPipelineStatus().then(setStatus).catch(() => setFailed(true)) }, []); return <div className="pipeline-page"><header className="pipeline-header"><div><p className="eyebrow">PLATFORM OBSERVABILITY</p><h1>Data Pipeline</h1><p>How raw sales records become distributed business intelligence.</p></div><div className={`pipeline-health ${failed ? 'offline' : ''}`}><span className="status-dot"/>{failed ? 'Status unavailable' : 'Pipeline healthy'}</div></header><section className="pipeline-flow">{stages.map(([Icon, title, copy], index) => { const StageIcon = Icon as typeof FileSpreadsheet; return <div className="flow-item" key={title as string}><article className="pipeline-node"><span><StageIcon size={18}/></span><div><h2>{title as string}</h2><p>{copy as string}</p></div></article>{index < stages.length - 1 && <ArrowDown className="flow-arrow" size={17}/>}</div> })}</section><section className="pipeline-details"><div className="tech-grid"><article><span>Data Source</span><strong>{status?.data_source ?? 'sales.csv'}</strong></article><article><span>Processing Engine</span><strong>{status?.processing_engine ?? 'Apache Spark'}</strong></article><article><span>API</span><strong>{status?.api ?? 'FastAPI'}</strong></article><article><span>Frontend</span><strong>{status?.frontend ?? 'React'}</strong></article><article><span>Records Processed</span><strong>{status ? number.format(status.records_processed) : <LoadingSkeleton className="inline-skeleton"/>}</strong></article><article><span>Pipeline Status</span><strong className={failed ? 'negative' : 'positive'}>{failed ? 'Unavailable' : 'Healthy'}</strong></article></div></section><section className="processing"><div><p className="eyebrow">TRANSFORMATION CONTRACT</p><h2>Data Processing Steps</h2><p>Each stage is applied in PySpark before analytics are exposed to the application.</p></div><div className="steps-grid">{steps.map(([title, copy], index) => <article key={title}><b>{String(index + 1).padStart(2, '0')}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="spark-info"><div className="spark-info-icon"><Sparkles size={23}/></div><div><h2>Why Apache Spark?</h2><p>Spark supports distributed processing for datasets that can outgrow a single machine’s memory, while PySpark makes those capabilities available through Python. SparkSight uses this architecture to demonstrate a scalable workflow that can be extended to significantly larger datasets.</p></div></section></div> }
